7682:
  box1:
    photek_amp_digiIndex: 0
    photek_time_digiIndex: 0
    photek_name: photek
    photek_lowAmpCut: 50
    photek_highAmpCut: 850
    left_amp_digiIndex: 10
    left_time_digiIndex: 1
    left_name: top_left
    left_lowAmpCut: 100
    left_highAmpCut: 750
    right_amp_digiIndex: 13
    right_time_digiIndex: 4
    right_name: top_right
    right_lowAmpCut: 100
    right_highAmpCut: 750
    x_min: -10
    x_max: 35
    bar_center_x: 13.5
    bar_halfwidth_x: 15.5
    y_min: 0
    y_max: 40
    bar_center_y: 28.5
    bar_halfwidth_y: 1.5   
  box2:
    photek_amp_digiIndex: 0
    photek_time_digiIndex: 0
    photek_name: photek
    photek_lowAmpCut: 50
    photek_highAmpCut: 850
    left_amp_digiIndex: 11
    left_time_digiIndex: 2
    left_name: middle_left
    left_lowAmpCut: 100
    left_highAmpCut: 750
    right_amp_digiIndex: 14
    right_time_digiIndex: 5
    right_name: middle_right
    right_lowAmpCut: 100
    right_highAmpCut: 750
    x_min: -10
    x_max: 35
    bar_center_x: 13.5
    bar_halfwidth_x: 15.5
    y_min: 0
    y_max: 40
    bar_center_y: 24.75
    bar_halfwidth_y: 1.5   
  box3:
    photek_amp_digiIndex: 0
    photek_time_digiIndex: 0
    photek_name: photek
    photek_lowAmpCut: 50
    photek_highAmpCut: 850
    left_amp_digiIndex: 12
    left_time_digiIndex: 3
    left_name: bottom_left
    left_lowAmpCut: 100
    left_highAmpCut: 750
    right_amp_digiIndex: 15
    right_time_digiIndex: 6
    right_name: bottom_right
    right_lowAmpCut: 100
    right_highAmpCut: 750
    x_min: -10
    x_max: 35
    bar_center_x: 13.5
    bar_halfwidth_x: 15.5
    y_min: 0
    y_max: 40
    bar_center_y: 21.25
    bar_halfwidth_y: 1.5   
